// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhVcSKOEp0xF1L9P3cR2K_841cw76W9pU',
    appId: '1:206202285763:web:513bd7932bb33a574c7c76',
    messagingSenderId: '206202285763',
    projectId: 'pelatihan-mobile-flutter',
    authDomain: 'pelatihan-mobile-flutter.firebaseapp.com',
    storageBucket: 'pelatihan-mobile-flutter.firebasestorage.app',
    measurementId: 'G-QXYWCEY8LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiMpekGNxgTtm2HxlnJ5O-PrXIUQeccCU',
    appId: '1:206202285763:android:9548800b31726b894c7c76',
    messagingSenderId: '206202285763',
    projectId: 'pelatihan-mobile-flutter',
    storageBucket: 'pelatihan-mobile-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeZs7RMBYfdctj5pBmGZ-ynTN4DQ_DHgo',
    appId: '1:206202285763:ios:3d374f53ffae019c4c7c76',
    messagingSenderId: '206202285763',
    projectId: 'pelatihan-mobile-flutter',
    storageBucket: 'pelatihan-mobile-flutter.firebasestorage.app',
    iosBundleId: 'com.pelatihan.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeZs7RMBYfdctj5pBmGZ-ynTN4DQ_DHgo',
    appId: '1:206202285763:ios:3d374f53ffae019c4c7c76',
    messagingSenderId: '206202285763',
    projectId: 'pelatihan-mobile-flutter',
    storageBucket: 'pelatihan-mobile-flutter.firebasestorage.app',
    iosBundleId: 'com.pelatihan.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhVcSKOEp0xF1L9P3cR2K_841cw76W9pU',
    appId: '1:206202285763:web:abf4591e54ef71824c7c76',
    messagingSenderId: '206202285763',
    projectId: 'pelatihan-mobile-flutter',
    authDomain: 'pelatihan-mobile-flutter.firebaseapp.com',
    storageBucket: 'pelatihan-mobile-flutter.firebasestorage.app',
    measurementId: 'G-N650P34N18',
  );
}
